### ISSUE TITLE
Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by logicfish** [JamborJan/paperwork#50]
```
npm WARN gulp-jshint@2.1.0 requires a peer of jshint@2.x but none was installed.
bower invalid-meta  for:/opt/app/paperwork/frontend/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower extra-resolution      Unnecessary resolution: angular-animate#~1.2
bower extra-resolution      Unnecessary resolution: angular-resource#~1.2
bower extra-resolution      Unnecessary resolution: angular-route#~1.2
module.js:472
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/app/paperwork/frontend/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).
npm WARN gulp-jshint@2.1.0 requires a peer of jshint@2.x but none was installed.
bower invalid-meta  for:/opt/app/paperwork/frontend/bower.json
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower extra-resolution      Unnecessary resolution: angular-animate#~1.2
bower extra-resolution      Unnecessary resolution: angular-resource#~1.2
bower extra-resolution      Unnecessary resolution: angular-route#~1.2
module.js:472
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/app/paperwork/frontend/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).

```

**Comment by logicfish** [comment]
I had to ssh and do:
```
vagrant@localhost:~$ cd /opt/app/paperwork/frontend/
vagrant@localhost:~$ npm install jshint gulp-jshint --save-dev

```

**Comment by JamborJan** [comment]
Hey @logicfish thank you for submitting this issue and sorry for the late reply. I will look into that as soon as possible.

**Comment by JamborJan** [comment]
This project is dormant ([reasons](https://gist.github.com/JamborJan/8e42eff813b6fb0b6fe987afb9241c5e)). 

Issues will be closed as there will be no further progress on them. Feel free to fork the repo and take over maintenance.
